version: '4.2'
services:
    user:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8001:8000
        volumes:
            - .:/app
        command: 'php artisan serve --host=0.0.0.0'
        depends_on:
            - user_db

    user_db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: user
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - ./storage/dbdata:/var/lib/mysql
        ports:
            - 33064:3306
